### ISSUE TITLE
How to observe HID output from zmk keyboard?

### ISSUE THREAD

**Issue by stites** [dnaq/plover-machine-hid#3]
So close! I now have plover-machine-hid plugin working, running under plover-flake. My firmware also compiles, so that's something. I've booted up plover and selected the "Plover HID" machine and bound all the keys (to themselves). My configuration looks like this:

![2022-10-27_14-46](https://user-images.githubusercontent.com/1694705/198373641-986edd1f-6046-4c89-9144-75c856862bbb.png)

Unfortunately, I still can't see any output from my board. I know that the firmware contains the layout but the keyboard seems unresponsive on this layer. To make sure this isn't a permissions error, I've also run plover under root (and repeated all the same steps) and I still seem to be in the same situation.

Could you let me know how to observe HID events or point me in a direction of where to figure this out? you mentioned that zmk won't emit these events as keyboard events: how can I observe these? I can probably sift through any code issues I come across but am less certain about these hardware details.

**Comment by stites** [comment]
Maybe I need some udev rules for the 0xff vendor to detect events? I was thinking I wouldn't have to do this if I was root.

**Comment by dnaq** [comment]
I believe the plugin issue tracker to be the wrong forum for support. Have you considered using the plover discord server?

That being said you can do the following to see if the keyboard actually emits any steno keystrokes or not:

```
> nix-shell -p python3Packages.hid
> python3
>> import hid
>> hid.enumerate()
```
That should give you a list of all of your hid devices, and any devices found with the usage_page 65360 and the usage 19542 should be plover hid devices. If you don't find any plover hid devices at all then your firmware isn't working.

Then you could try opening and reading from them by doing:
```
>> d = hid.Device(path=<path you saw in the output of the previous command>)
>> d.read(65536)
```

If you get any output when hitting the keys on the plover layer, then everything works well on the firmware end, if you don't and had other devices with the same usage_page and usage, try those.

If you have multiple devices and one of them works, it's most probably because you're connected over USB but have the keyboard in bluetooth mode, if that's the case just either switch the output mode to USB and try again, or pull the USB cable and reset the plugin and try again (the plugin always connects to the first device it finds).

If you can see and connect to all devices, but don't get any output from either of them, then something is probably wrong with your firmware.

**Comment by stites** [comment]
Thank you for helping me through all of this! I deeply appreciate it and am happy to report that everything is working perfectly. I started by asking on the LOWPROKB discord. Next time I will start on the plover discord.

**Comment by jthlim** [comment]
In case it helps anyone trying to do this in the future, you can use this: https://lim.au/#/software/plover-hid
